---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: remote_server
  become: true
  roles:
    - NTP
    - Packages
    - SQL
    - Message_Queue
    - Memcached
    - Etcd
